### ISSUE TITLE
get_current_session returns None

### ISSUE THREAD

**Issue by dishiwujian** [dound/gae-sessions#12]
The error log as below:

```
Traceback (most recent call last):
File "/base/python_runtime/python_lib/versions/1/google/appengine/ext/webapp/__init__.py", line 511, in __call__
  handler.get(*groups)
File "/base/data/home/apps/guessnumberftw/1.345814701810313210/guessnum.py", line 49, in get
  if session.is_active():
AttributeError: 'NoneType' object has no attribute 'is_active'
```

I have already had 'appengine_config.py' which is copy from 'demo-with-google-logins', but it still donesn't work.

**Comment by dound** [comment]
Are you sure the middleware is being installed?  `get_current_session()` will _never_ return `None` unless the middleware doesn't run.  You might want to use a debugger or a logging statement to double-check whether the middleware code is being run or not.

**Comment by dishiwujian** [comment]
Thanks for answering. 
Now I find where the problem is. 
I'v used wsgiref.handlers.CGIHandler().run(application) in the main(). I change it to run_wsgi_app(application), and it works. 
However, I still dont know why.

**Comment by dound** [comment]
The latter (run_wsgi_app()) calls a function which includes the middleware you specified in appengine_config.py - the former does not perform this step.  For details, check out the comments and implementation of [run_wsgi_app()](http://www.google.com/codesearch/p?hl=en#Qx8E-7HUBTk/trunk/python/google/appengine/ext/webapp/util.py&q=run_wsgi_app%20package:http://googleappengine%5C.googlecode%5C.com&l=71).
