### ISSUE TITLE
Allow gae sessions to expire at browser close

### ISSUE THREAD

**Issue by eliasnaur** [dound/gae-sessions#14]
Cookies expiration dates can be set to the special value, 0, which means that the cookie should be forgotten when the browser closes. However, this special value doesn't seemt to be supported in gae-sessions. I'll attach a patch that works for me. I found that the code currently depends on unix timestamps being exactly 10 characters long, which is mildly disturbing, and means that I had to zero-extend the timestamp for it to work with '0'.

**Comment by dound** [comment]
This seems identical (minus the patch) to issue 15 so I'll close this copy.
