### ISSUE TITLE
Corrupt session data isn't handled gracefully

### ISSUE THREAD

**Issue by chriswa** [dound/gae-sessions#16]
Firstly, thanks for this great little library! <3

During development, I like to move around and rename classes. I'm storing instances in my sessions, so when gaesessions unpickles my objects which no longer match up with classes, everything explodes.

My fix was to wrap __decode_data() in a try: ... except: return None.

**Comment by dound** [comment]
Thanks Chris!  This is a good point.  I'll address this in the next release (in the next week or so).  I suspect I'll do something similar to your fix, though I'll probably log a warning too.

Thanks for sharing this issue and your patch!

**Comment by dound** [comment]
Well my "or so" was much longer than it should have been but I've finally pulled in your suggestion (commit 26abd5654252b8a3cdb9cc653721fab7a5ff89a7).
