### ISSUE TITLE
problem solved

### ISSUE THREAD

**Issue by ghost** [dound/gae-sessions#17]
Problem solved. I can't delete this post.

**Comment by ghost** [comment]
solved

**Comment by dound** [comment]
It looks like you figured it out, but I'll post the solution here in case anyone else needs it.

The gae-sessions cookies specify `HttpOnly` by default.  This makes the cookie inaccessible to JavaScript.  Thus to access cookies with JavaScript, remove the `; HttpOnly` from the end of the `COOKIE_FMT` variable.
