### ISSUE TITLE
warning log under django

### ISSUE THREAD

**Issue by ghost** [dound/gae-sessions#18]
The app "gaesessions" contains imports in its **init**.py (at least hmac, os, datetime, .os, google, time, logging, base64, .google, .datetime, pickle, Cookie, .base64, .pickle, .hmac, .time, .Cookie, hashlib, .hashlib, .logging). This can cause strange bugs due to recursive imports! You should either do the import lazily (within functions) or ignore the app settings/urlsauto with IGNORE_APP_SETTINGS and IGNORE_APP_URLSAUTO in your settings.py.

**Comment by dound** [comment]
Hmm, I'm not familiar enough with Django to understand how these imports can cause an issue.  Can you provide a specific example of where this breaks?  Perhaps attach a tarball/zip of a small project which demonstrates the problem.  Thanks!

**Comment by ghost** [comment]
This log only happen in cold start.

**Comment by dound** [comment]
Still not sure what the issue is - can you post sample code which demonstrates the problem?  Thanks!

**Comment by ghost** [comment]
settings.py
INSTALLED_APPS = (
     'gaesessions',
)

MIDDLEWARE_CLASSES = (
    'gaesessions.DjangoSessionMiddleware',
)

**Comment by dound** [comment]
Not a bug as far as I can tell.  If you have a complete code sample (e.g., a small Django-based GAE project) which demonstrates a problem then I'll re-open this issue.
