### ISSUE TITLE
Deleting old session data

### ISSUE THREAD

**Issue by amirshim** [dound/gae-sessions#2]
Sessions often don't get deleted from the datastore, and need to be cleaned up. For example, when the user lets the cookie expire.

The only two ways I can think of cleaning up (as it is right now):
1. delete all SessionModel objects in the datastore -- will also delete some live sessions (bad)
2. traverse all SessionModel objects in the datastore, unmarshal them and delete ones with old expirations

A better way to deal with this (in my opinion)  is to prepend a creation time to the sid ( "1273169252_cc4a5...8aec5" ) so that we can simply do a key-only query for old keys (i.e. **key** < a specific time). This also lets us avoid loading the payload when we do these types of deletes. Another benefit of this, is reducing the chances of sid collisions.  The only way a collision can happen with this type of ssid is if two md5(os.urandom(16)) calls return the same hash in the same second.

**Comment by dound** [comment]
Thanks Amir -- this is a great point!  I like your solution too -- as you pointed out, prefixing the random portion of the sid with the expiration timestamp would enable us to do a keys-only query when we want to cleanup old sessions.  Awesome!

Once this improvement has been added, I'll also create a function which performs the cleanup so that a cronjob can be easily created to manage the cleanup of old sessions.

**Comment by dound** [comment]
The latest release (v0.05) implements your suggestions.  In particular, there is now a [delete_expired_sessions](http://github.com/dound/gae-sessions/commit/f9cc1fb8595b039835cef5635a15e56cf55d28f6) function which cleans up expired sessions.  The demo code also includes an example cronjob for automating the cleanup process.

Thanks again for the suggestion; I've credited you for it on the [wiki page](http://wiki.github.com/dound/gae-sessions/).

**Comment by amirshim** [comment]
Wow that was fast! Great work and thanks for the credit.  There's one tiny bug... don't even know if to call it a bug, but you have 28 years to fix it.  In 2038, Posix time will become an long :) Again... great work.
http://en.wikipedia.org/wiki/Year_2038_problem

**Comment by dound** [comment]
Haha, I'll make sure to come back and patch it when the 2038 apocalypse is closer.  In the meantime, hopefully nobody will use an expiration date a billion seconds in the future (like AOL).  :)
