### ISSUE TITLE
Picking up cookies from os.environ doesn't work with WebTest

### ISSUE THREAD

**Issue by AsadR** [dound/gae-sessions#22]
gaesessions doesn't work while unit testing under WebTest-1.2.3 and NoseGAE 0.1.7.

The issue is with the cookies being read from os.environ['HTTP_COOKIE']. Webtest doesn't seem to set that env variable. If I manually set it before making the get request it works fine.

More details here:
http://stackoverflow.com/questions/5348896/nosegae-unit-tests-with-gae-session-on-a-python-google-app-engine-project/

**Comment by dound** [comment]
[Calvin](http://stackoverflow.com/users/556900/calvin) answered Asad's question.  The solution was to manually set `os.environ['HTTP_COOKIE']` before the `self.app.get()` request.
