### ISSUE TITLE
Session not Initiated

### ISSUE THREAD

**Issue by marklooi** [dound/gae-sessions#24]
Using gae-sessions in Windows 7, 64-bit application. I am running into a problem where the session isn't initiated, therefore all subsequent session-related activity can't proceed. It does not occur on Windows XP and when deployed to appspot, for example. Any one running into similar problems?

**Comment by dound** [comment]
Strange.  What version of python are you using?

**Comment by rickxu** [comment]
after user sign in success, I put user info into session.
session = get_current_session()
session[SessionKey.CURRENT_USER] = u
session.regenerate_id()

but another page will need to check whether user has login

"""
return current user in session or none
 """
session = get_current_session()
return session.get(SessionKey.CURRENT_USER, None)

but it always could not get user info, when I debug, i find the session was not initiated.
For xp, python 2.7, it is okay. but for win7 64-bit, python 2.7, it could not work.

Do u know what thing was ignored? or what need I do to initiate session?

**Comment by dound** [comment]
GAE uses Python 2.4 - please use that version and expect the library will work as you expect.  If not, let me know and I'll re-open the issue.

**Comment by zystemsgo** [comment]
I was having a similiar issue on Windows 7 64 bit.  When I ran directly through gae development tool, everything worked fine but when I ran the code through wing ide, it would not get a session.   After a week of racking my brain, I finally figured out the problem.   We put DEFAULT_LIFETIME = datetime.timedelta(hours=1) and originally it was DEFAULT_LIFETIME = datetime.timedelta(days=7).   Not sure why wing debugger would prevent the browser from getting a session.   The interesting thing is the original code change with hours=1 works fine on linux with wing debugger.   Why would this problem occur?  Any ideas?

**Comment by rickxu** [comment]
as I remembered, after we used the latest code of gae session, it worked

2012-04-13

徐元伟

发件人：zystemsgo
发送时间：2012-04-13 10:26
主题：Re: [gae-sessions] Session not Initiated (#24)
收件人："rickxu"hitxyw@126.com
抄送：

I was having a similiar issue on Windows 7 64 bit.  When I ran directly through gae development tool, everything worked fine but when I ran the code through wing ide, would not get a session.   After a week of racking my brain, I finally figured out the problem.   We put DEFAULT_LIFETIME = datetime.timedelta(hours=1) and originally it was DEFAULT_LIFETIME = datetime.timedelta(days=7).   Not sure why wing debugger would prevent the browser from getting a session.   The interesting thing is the original code change with hours=1 works fine on linux with wing debugger.   Why would this problem occur?  Any ideas? 

---

**Comment by zystemsgo** [comment]
When I make the change from  DEFAULT_LIFETIME = datetime.timedelta(days=7) to DEFAULT_LIFETIME = datetime.timedelta(hours=1), it works from the command line or through gae launcher.   When I try to run the same thing through a debugger such as Wing or Pycharm, it does not create a session.   Very Strange!

Thanks
-Dimitry

**Comment by zystemsgo** [comment]
After talking to the developer of Wing IDE, he said Windows users will probably want to set the TZ environment variable to UTC via the environment field in Project Properties to work around problems with setting os.environ['TZ'] while a process is running (see Issues on Microsoft Windows for details about the Windows runtime bug)...here is the link for runtime bug (http://wingware.com/doc/install/trouble-win32)

Thanks
-Dimitry
