### ISSUE TITLE
Del example

### ISSUE THREAD

**Issue by sylvainvivien** [dound/gae-sessions#26]
In the example : del session.blah  # remove 'blah' from the session

I think it should be

del session['blah']  # remove 'blah' from the session

Regards

**Comment by dound** [comment]
Oops, that was a silly mistake - thanks for pointing it out.  I'll correct the readme's example tomorrow.  Thanks for the heads up!

**Comment by dound** [comment]
Fixed in 6cd97c149da681c94b24679b020ffb9dfab9700d.  Thanks again for pointing this out.
