### ISSUE TITLE
global _current_session, python 2.7, Thread Safe ?

### ISSUE THREAD

**Issue by sylvainvivien** [dound/gae-sessions#27]
Hi,

GAE should be multi-threaded with python 2.7.

gae-sessions use global _current_session, so I think it will not be "compatible" ?
What do you think about it ?

There is a topic about GAE/Thread-Safe here : https://groups.google.com/forum/#!topic/google-appengine/QUXR8jy1CMg

Regards

Sylvain

**Comment by dound** [comment]
You're right - to be thread-safe that global variable will need to be
tweaked so that to be thread local.  2.7 is still a little ways off for app
engine I believe but I'll get this change in soon so the library is ready
for it.

Thanks for the heads up!

~ David
On Jul 2, 2011 12:57 AM, "sylvainvivien" <
reply@reply.github.com>
wrote:

**Comment by dound** [comment]
Thanks Sylvain; I've made the necessary change so that gae-sessions is now thread-safe (commit 2697b82c96a3e5a650e6420e4d00bb4c8f864a7c).  This is part of the [gae-sessions v1.07 release](https://github.com/dound/gae-sessions/tree/v1.07).

Thanks for suggesting this improvement!

**Comment by sylvainvivien** [comment]
Hi, thank you for the fast update !

I just wonder if you have to use the statement "global"

Currently you did :

```
def __call__(self, environ, start_response):
        # initialize a session for the current user
        _tls.current_session = Session(lifetime=self.lifetime, no_datastore=self.no_datastore, cookie_only_threshold=self.cookie_only_thresh, cookie_key=self.cookie_key)
```

I think it works because _tls is mutable ?

But don't you think it should be :

```
def __call__(self, environ, start_response):
        # initialize a session for the current user
        global _tls  # <----- global ?      
        _tls.current_session = Session(lifetime=self.lifetime, no_datastore=self.no_datastore, cookie_only_threshold=self.cookie_only_thresh, cookie_key=self.cookie_key)
```

I think about it because I was reading this : http://stackoverflow.com/questions/104983/what-is-thread-local-storage-in-python-and-why-do-i-need-it

Great job

Sylvain

**Comment by dound** [comment]
I initially misread your comment above.  Anyway, [global](http://docs.python.org/release/2.4/ref/global.html) enables you to assign to a global variable.  We are assigning to an _attribute_ of `_tls`, not `_tls` itself so we don't need `global _tls`.
