### ISSUE TITLE
add support for Django

### ISSUE THREAD

**Issue by trungpham** [dound/gae-sessions#3]
Can you create a MiddleWare for Django?

So we can access it via request.session.

Thanks.

**Comment by dound** [comment]
gae-sessions v1.01 adds DjangoSessionMiddleware which enables gae-sessions to work with Django.  Check out the updated [readme](http://github.com/dound/gae-sessions#readme) for information on how to use it (it should be pretty straightforward).

(It's too bad Django doesn't support standard WSGI middleware.)
