### ISSUE TITLE
Where is settings.py?

### ISSUE THREAD

**Issue by zakdances** [dound/gae-sessions#30]
In the readme it says "If you want to gae-sessions with Django, add 'gaesessions.DjangoSessionMiddleware' to your list of MIDDLEWARE_CLASSES in your settings.py file." Where is settings.py?

**Comment by zakdances** [comment]
I created a settings.py file in my root project dir, but I'm not sure if Django or anything else is actually reading it. It would be helpful if the documentation was a little more clear about this particular file. Also, where is the best place to go if I need some help with GAE-Sessions? I don't want post irrelevant stuff to Issues.

**Comment by dound** [comment]
The settings.py file is a file created by the django-admin.py script when you use it create a Django project.  If you don't have such a file, then perhaps you can define `MIDDLEWARE_CLASSES` somewhere else - really depends on your particular Django setup though.

**Comment by zakdances** [comment]
Thanks Dave.
