### ISSUE TITLE
Redundant loggin.info in gaesessions/__init__.py

### ISSUE THREAD

**Issue by eliasnaur** [dound/gae-sessions#32]
I think a debug logging.info was sneaked in along with the Varying header changes. Consider applying the following patch:

--- **init**.py.old 2011-11-03 09:52:36.901687097 +0100
+++ **init**.py 2011-11-03 09:52:39.677700872 +0100
@@ -487,7 +487,6 @@
             self.response_handler = None
         if request.session.is_accessed():
             from django.utils.cache import patch_vary_headers
-            logging.info("Varying")
           patch_vary_headers(response, ('Cookie',))
       return response

**Comment by dound** [comment]
Oops, good catch.  I've applied the patch: 36c7fd269

It will go out in the next release, which should be relatively soon (a minor tweak in the demo was made so that its json library import works on both the old and new runtime).
