### ISSUE TITLE
Works in python2.5, not in 2.7

### ISSUE THREAD

**Issue by Habel** [dound/gae-sessions#37]
So after attempting to migrate my project to python2.7, I learned that sessions is not working in python 2.7.

The error seems to stem from appengine_config.py. This issue could stem from my incompetence.

Here is the error message:

```
Traceback (most recent call last):
  File "c:\Program Files (x86)\Google\google_appengine\google\appengine\runtime\wsgi.py", line 195, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "d:\Documents\dna_manip\gaesessions\__init__.py", line 472, in __call__
    return self.app(environ, my_start_response)
TypeError: 'NoneType' object is not callable
```

**Comment by soundofjw** [comment]
I am not having this problem on Python 2.7 with Google App Engine. :/

**Comment by Habel** [comment]
So I assume it's because I did something wrong while migrating. Crap.
