### ISSUE TITLE
has_key throws AttributeError if it doesn't exist

### ISSUE THREAD

**Issue by jdeibele** [dound/gae-sessions#5]
Trying your demo:

 class LogoutPage(webapp.RequestHandler):
    def get(self):
        session = get_current_session()
        if session.has_key('me'):
            # update the user's record with total views
            myuser = session['me']
            myuser.past_view_count += session['pvsli']
            myuser.put()
            session.terminate()
            redirect_with_msg(self, 'Logout complete: goodbye ' + myuser.user.nickname())
        else:
            redirect_with_msg(self, "How silly, you weren't logged in")

and I get 

ERROR    2010-07-30 05:00:05,329 **init**.py:391] 'NoneType' object has no attribute 'has_key'

   if session.has_key('me'):
AttributeError: 'NoneType' object has no attribute 'has_key'

Other than that, things are looking good.  Thanks for writing gae-sessions.

**Comment by dound** [comment]
Good catch.  This is really an issue with the demo - the methods which access session data (except setters like `__setitem__`) all assume that they will only be called when on a live session object (since I expect this is the common case for most apps).   The simple fix: the `if` statement should check `session.is_active()` before calling `has_key()`.  I'll update the demo later today.  I should probably also update the documentation to communicate which methods should only be called on an active session.

**Comment by jdeibele** [comment]
I tried implementing what I think you're saying:
        if session.is_active() and session.has_key('me'):

and got AttributeError
       if session and session.has_key('me'): 

works.   Not sure what the implications of using "if session" instead of "if session.is_active" are.   I'm assuming that there's lots of people who hit a page and go away without registering.

**Comment by dound** [comment]
Oops, I misread your initial post.  The error is that `session` itself is `None`.  This should **never** happen.  It sounds like the `SessionMiddleware` isn't installed - that's the only way `get_current_session()` would return `None`.  Can you check to see if you've installed the `SessionMiddleware` middleware (e.g., with `appengine_config.py`)?

**Comment by jdeibele** [comment]
Arggghhh.    That's it.   I'm really sorry - I started this project by copying from another project but I didn't copy *.py and that obviously includes appengine_config.py.

I've copied it over and it's now working fine, including 

```
    if session.is_active() and session.has_key('me'):
```

when there's been no session

Thanks again.

**Comment by dound** [comment]
No problem, glad it works as expected now :).  Enjoy!
