### ISSUE TITLE
may fail with the new app engine 1.3.6 "namespace" feature

### ISSUE THREAD

**Issue by owebeeone** [dound/gae-sessions#8]
namespaces change the behaviour of datastore and memcache.  For session management, it seems it's important to use a specific namespace to avoid accidently missing session data.

Here is a patch.  It may work in earlier SDK's than 1.3.6 but you need to wait for the 1.3.6 release to deploy unless you registered your app as a trusted tester.

Patch: http://pastebin.com/raw.php?i=WPpBjNyM

**Comment by owebeeone** [comment]
I didn't expect that it would treat the patch output as markup....  How about a base64 version of the patch.  Decode with "base64 -d".

LS0tIG9sZC9fX2luaXRfXy5weQkyMDEwLTA4LTA3IDAzOjM1OjEzLjgyNDkxMDAwMCArMTAwMAor
KysgX19pbml0X18ucHkJMjAxMC0wOC0xMyAwODowMjozNi43MDI2NzMwMDAgKzEwMDAKQEAgLTIz
OCw3ICsyMzgsNyBAQAogICAgICAgICBpZiBzZWxmLnNpZDoKICAgICAgICAgICAgIHNlbGYuX19j
bGVhcl9kYXRhKCkKICAgICAgICAgc2VsZi5zaWQgPSBzaWQKLSAgICAgICAgc2VsZi5kYl9rZXkg
PSBkYi5LZXkuZnJvbV9wYXRoKFNlc3Npb25Nb2RlbC5raW5kKCksIHNpZCkKKyAgICAgICAgc2Vs
Zi5kYl9rZXkgPSBkYi5LZXkuZnJvbV9wYXRoKFNlc3Npb25Nb2RlbC5raW5kKCksIHNpZCwgbmFt
ZXNwYWNlPScnKQogCiAgICAgICAgICMgc2V0IHRoZSBjb29raWUgaWYgcmVxdWVzdGVkCiAgICAg
ICAgIGlmIG1ha2VfY29va2llOgpAQCAtMjQ3LDcgKzI0Nyw3IEBACiAgICAgZGVmIF9fY2xlYXJf
ZGF0YShzZWxmKToKICAgICAgICAgIiIiRGVsZXRlcyB0aGlzIHNlc3Npb24gZnJvbSBtZW1jYWNo
ZSBhbmQgdGhlIGRhdGFzdG9yZS4iIiIKICAgICAgICAgaWYgc2VsZi5zaWQ6Ci0gICAgICAgICAg
ICBtZW1jYWNoZS5kZWxldGUoc2VsZi5zaWQpICMgbm90IHJlYWxseSBuZWVkZWQ7IGl0J2xsIGdv
IGF3YXkgb24gaXRzIG93bgorICAgICAgICAgICAgbWVtY2FjaGUuZGVsZXRlKHNlbGYuc2lkLCBu
YW1lc3BhY2U9JycpICMgbm90IHJlYWxseSBuZWVkZWQ7IGl0J2xsIGdvIGF3YXkgb24gaXRzIG93
bgogICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgIGRiLmRlbGV0ZShzZWxmLmRiX2tl
eSkKICAgICAgICAgICAgIGV4Y2VwdDoKQEAgLTI1Nyw3ICsyNTcsNyBAQAogICAgICAgICAiIiJT
ZXRzIHRoZSBkYXRhIGFzc29jaWF0ZWQgd2l0aCB0aGlzIHNlc3Npb24gYWZ0ZXIgcmV0cmlldmlu
ZyBpdCBmcm9tCiAgICAgICAgIG1lbWNhY2hlIG9yIHRoZSBkYXRhc3RvcmUuICBBc3N1bWVzIHNl
bGYuc2lkIGlzIHNldC4gIENoZWNrcyBmb3Igc2Vzc2lvbgogICAgICAgICBleHBpcmF0aW9uIGFm
dGVyIGdldHRpbmcgdGhlIGRhdGEuIiIiCi0gICAgICAgIHBkdW1wID0gbWVtY2FjaGUuZ2V0KHNl
bGYuc2lkKQorICAgICAgICBwZHVtcCA9IG1lbWNhY2hlLmdldChzZWxmLnNpZCwgbmFtZXNwYWNl
PScnKQogICAgICAgICBpZiBwZHVtcCBpcyBOb25lOgogICAgICAgICAgICAgIyBtZW1jYWNoZSBs
b3N0IGl0LCBnbyB0byB0aGUgZGF0YXN0b3JlCiAgICAgICAgICAgICBpZiBzZWxmLm5vX2RhdGFz
dG9yZToKQEAgLTMwNSw3ICszMDUsNyBAQAogICAgICAgICAgICAgIyBsYXRlc3QgZGF0YSB3aWxs
IG9ubHkgYmUgaW4gdGhlIGJhY2tlbmQsIHNvIGV4cGlyZSBkYXRhIGNvb2tpZXMgd2Ugc2V0CiAg
ICAgICAgICAgICBzZWxmLmNvb2tpZV9kYXRhID0gJycKIAotICAgICAgICBtZW1jYWNoZS5zZXQo
c2VsZi5zaWQsIHBkdW1wKSAgIyBtYXkgZmFpbCBpZiBtZW1jYWNoZSBpcyBkb3duCisgICAgICAg
IG1lbWNhY2hlLnNldChzZWxmLnNpZCwgcGR1bXAsIG5hbWVzcGFjZT0nJykgICMgbWF5IGZhaWwg
aWYgbWVtY2FjaGUgaXMgZG93bgogCiAgICAgICAgICMgcGVyc2lzdCB0aGUgc2Vzc2lvbiB0byB0
aGUgZGF0YXN0b3JlCiAgICAgICAgIGlmIGRpcnR5IGlzIFNlc3Npb24uRElSVFlfQlVUX0RPTlRf
UEVSU0lTVF9UT19EQiBvciBzZWxmLm5vX2RhdGFzdG9yZToKQEAgLTQ3MCw4ICs0NzAsOCBAQAog
ICAgIFJldHVybnMgVHJ1ZSBpZiBhbGwgZXhwaXJlZCBzZXNzaW9ucyBoYXZlIGJlZW4gcmVtb3Zl
ZC4KICAgICAiIiIKICAgICBub3dfc3RyID0gdW5pY29kZShpbnQodGltZS50aW1lKCkpKQotICAg
IHEgPSBkYi5RdWVyeShTZXNzaW9uTW9kZWwsIGtleXNfb25seT1UcnVlKQotICAgIGtleSA9IGRi
LktleS5mcm9tX3BhdGgoJ1Nlc3Npb25Nb2RlbCcsIG5vd19zdHIgKyB1J1x1ZmZmZCcpCisgICAg
cSA9IGRiLlF1ZXJ5KFNlc3Npb25Nb2RlbCwga2V5c19vbmx5PVRydWUsIG5hbWVzcGFjZT0nJykK
KyAgICBrZXkgPSBkYi5LZXkuZnJvbV9wYXRoKCdTZXNzaW9uTW9kZWwnLCBub3dfc3RyICsgdSdc
dWZmZmQnLCBuYW1lc3BhY2U9JycpCiAgICAgcS5maWx0ZXIoJ19fa2V5X18gPCAnLCBrZXkpCiAg
ICAgcmVzdWx0cyA9IHEuZmV0Y2goNTAwKQogICAgIGRiLmRlbGV0ZShyZXN1bHRzKQo=

**Comment by dound** [comment]
Thanks for the patch owebeeone!  I'll test it out and, once 1.3.6 is fully released, I'll apply it to the project.

PS.  I saw that github's markup processor mangled the patch, so I replaced the mangled text with a link to the raw text on pastebin.

**Comment by dound** [comment]
I've applied the patch - thanks again!
