### ISSUE TITLE
get_current_session returns None

### ISSUE THREAD

**Issue by fredrikbonander** [dound/gae-sessions#9]
While testing a new GAE application (1.3.7) w/ just gaesessions and webapp.template get_current_session() returns None in local enviorment.

Using this to test:
from gaesessions import get_current_session
import logging

session = get_current_session()
logging.info(session)

No entries are created in the datastore. 

Is this a problem in 1.3.7?

**Comment by fredrikbonander** [comment]
I fault. Missed the appengine_config. Please delete!

**Comment by dound** [comment]
No problem - enjoy gae-sessions!
